# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kirigami': '@stable'
    'libraries/kirigami-addons': '@latest'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kcrash': '@stable'
    'frameworks/kdnssd': '@stable'
